---
- name: Ansible Playbook for Docker Build, Run, and Push
  hosts: localhost
  become: no
  gather_facts: no

  vars:
    image: flashcard-app
    image_tag: latest
    docker_username: your_dockerhub_username
    docker_password: your_dockerhub_password
    ansible_python_interpreter: /usr/local/python/3.12.1/bin/python3

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: .
          pull: no
        name: "{{ image }}"
        tag: "{{ image_tag }}"
        source: build
      register: build_result

    - name: Check if the image was built
      ansible.builtin.debug:
        msg: "{{ build_result.stdout }}"

    - name: Run the Docker container
      community.docker.docker_container:
        name: "{{ image }}"
        image: "{{ image }}:{{ image_tag }}"
        state: started
        published_ports:
          - "8080:80"
        restart_policy: always

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Tag image for Docker Hub
      community.docker.docker_image:
        name: "{{ docker_username }}/{{ image }}"
        tag: "{{ image_tag }}"
        source: local

    - name: Push image to Docker Hub
      community.docker.docker_image_push:
        name: "{{ docker_username }}/{{ image }}"
        tag: "{{ image_tag }}"
      register: push_result

    - name: Show push result
      ansible.builtin.debug:
        msg: "{{ push_result.stdout }}"